name: Solicitar Funcionalidad
description: Proponer una nueva funcionalidad para la aplicación
title: "[FUNCIONALIDAD] "
labels: ["enhancement", "feature"]

body:
  - type: textarea
    id: feature-description
    attributes:
      label: Descripción de la funcionalidad
      description: Describe la funcionalidad que te gustaría ver
      placeholder: "Me gustaría que la aplicación pudiera..."
    validations:
      required: true
      
  - type: textarea
    id: use-case
    attributes:
      label: Caso de uso
      description: Explica cómo usarías esta funcionalidad
      placeholder: "Esta funcionalidad me ayudaría cuando..."
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Prioridad
      description: ¿Qué tan importante es esta funcionalidad?
      options:
        - Baja
        - Media
        - Alta
        - Crítica
    validations:
      required: true
      
  - type: checkboxes
    id: categories
    attributes:
      label: Categorías relacionadas
      description: Selecciona las categorías que aplican
      options:
        - label: Planificación de comidas
        - label: Lista de compras
        - label: Recetas
        - label: Nutrición
        - label: Batch Cooking
        - label: Comunidad
        - label: Configuración
        - label: Importación/Exportación