name: Moderar Receta
description: Reportar problema con una receta de la comunidad
title: "[MODERACIÓN] "
labels: ["moderation", "recipe"]

body:
  - type: input
    id: recipe-name
    attributes:
      label: Nombre de la receta
      description: Nombre de la receta problemática
      placeholder: "ej: Paella Valenciana"
    validations:
      required: true
      
  - type: textarea
    id: issue-description
    attributes:
      label: Descripción del problema
      description: Describe qué está mal con la receta
      placeholder: "La receta contiene..."
    validations:
      required: true
      
  - type: dropdown
    id: issue-type
    attributes:
      label: Tipo de problema
      options:
        - Contenido inapropiado
        - Información incorrecta
        - Spam
        - Receta duplicada
        - Estructura inválida
        - Otro
    validations:
      required: true
      
  - type: textarea
    id: suggested-fix
    attributes:
      label: Solución sugerida (opcional)
      description: Si tienes una sugerencia para arreglar el problema
      placeholder: "Sugiero que..."
      
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmación
      description: Por favor confirma que has revisado la receta
      options:
        - label: He revisado la receta y confirmo que hay un problema
          required: true
        - label: Entiendo que este reporte será revisado por moderadores
          required: true