name: Moderar Recetas

on:
  push:
    paths:
      - 'recipes/**'
      - 'scripts/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  moderate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
      - name: Moderar recetas
        run: |
          python scripts/moderate_recipes.py recipes
      - name: Actualizar metadatos
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add metadata.json moderation_report.txt || true
          git commit -m "chore: actualizar metadatos y reporte" || echo "sin cambios"
          git push || true
